[mypy]
ignore_missing_imports = True
allow_untyped_decorators = True
explicit_package_bases = True
exclude = .venv|tests|airflow|tests

[mypy-routes.debug]
ignore_errors = True

[mypy-services.upload_handler]
ignore_errors = True

[mypy-services.classifier]
ignore_errors = True

[mypy-services.detector]
ignore_errors = True

[mypy-db.repository]
ignore_errors = True